#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
      - step:
          name: Unit Tests
          deployment: test
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - python -m tests.test_runner
      - step:
            name: Document Generator
            caches:
              - pip
            script: 
              - pip install -r requirements.txt
              - pip install -U sphinx
              - pip install sphinx_rtd_theme
              - cd docs
              - make clean
              - sphinx-apidoc -o source ../filament_augmentation
              - make html
            artifacts:
              - sphinxdocs/_build/html/**
  branches:
    master:
      - step:
          name: python packaging
          deployment: production
          caches:
            - pip
          script:
          - pipe: atlassian/pypi-publish:0.3.1
            variables:
                PYPI_USERNAME: $PYPI_USER
                PYPI_PASSWORD: $PYPI_PASSWORD
                # REPOSITORY: '<string>' # Optional.
                DISTRIBUTIONS: sdist bdist_wheel
                # FOLDER: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.