#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - python -m tests.test_runner
      - step:
            name: doc generator
            caches:
              - pip
            script: 
              - pip install -r requirements.txt
              - pip install -U sphinx
              - pip install sphinx_rtd_theme
              - cd docs
              - make clean
              - sphinx-apidoc -o source ../filament_augmentation
              - make html
            artifacts:
              - sphinxdocs/_build/html/**
      